### PR TITLE
Add Ingredients to Recipe

### PR DESCRIPTION
**Pull request by ebramanti**
### Database
- URL for ingredient on relation, general URL on Node
- Amount of ingredient on relation
### Data Type

```
{
    id: Optional
    name: Required
    url: Optional
    amount: Required
    amountunit: Optional
}
```
### API
- `GET /ingredients`

```
[
   {
      "id": "25",
      "name": "apple",
      "url": (null, or "http://...),
      "tags": ["fruit"]
   },
   {
      "id": 121,
      "name": "orange",
      "url": null,
      "tags": ["fruit","citrus"]
   }
]
```
- `GET /recipes/:id/ingredients`
### Frontend
- Easy unit conversion
- Offering ingredient options

### CODE REVIEW

**Comment by AuthorOfTheSurf** [comment]
This still says it's being merged into master, amend that. The cql file I added is correct, but I can't get it to run successfully. Currently I am running it with:

```
rm -rf data/graph.db; cat ~/Repos/Ricetta/ingredients.cql | bin/neo4j-shell -path data/graph.db
```

And the shell is telling me that nodes are being created, but this is not reflected in the db. The database also isn't being wiped so the nodes must be getting written somewhere unexpected. Will look into tomorrow.

Check out the comment on d606c49

**Comment by AuthorOfTheSurf** [comment]
Recommend that we put the frontend tasks in a separate PR, those seem advanced for what were doing so far. Ingredients have tags so recommendations/substitutions could be done with that.

**Comment by ebramanti** [comment]
Pinging @juliancoleman on this.

**Comment by ebramanti** [comment]
Hey @AuthorOfTheSurf, let's talk about tags for ingredients. 

I think we should definitely avoid this... While it would provide extra search filtering, I believe it would be easier to perform searches on ingredients by name only.

I'm looking at the `GET /ingredients` example, for reference below:

```
[
    {
        "id": "25",
        "name": "apple",
        "url": (null, or "http://...),
        "tags": ["fruit"] // here
    },
    {
        "id": 121,
        "name": "orange",
        "url": null,
        "tags": ["fruit","citrus"] //and here
    }
]
```

**Comment by AuthorOfTheSurf** [comment]
But we want connections or some ordering to ingredient nodes, these nodes could be connected to tag nodes. Searches on tags would be fast and easy to implement.

> While it would provide extra search filtering, I believe it would be easier to perform searches on ingredients by name only.

Why not both? I would be disappointed to search "citrus salmon" and not get any recipes with lemon usage. And it certainly doesn't confuse the user at all, plus we can determine visibility.

I would say
- Allow tags, they allow easy searching and organization. They are a natural occurrence in our graph scheme. We want as many relations as humanly possible (!!!) they are cheap and in general the graph winds up being somewhat simple because data can be stored on nodes or relations.
- Take list of ingredients, possibly add to it, and use it as the starting list.
- We set up the initial tagging of ingredients. This is kind of hand-work, but it's not too bad to do the simple ones `:Tag:meat`, `:Tag:citrus`, `:Tag:spice`.
- Should we explore integrating a search engine api e.g. Duck Duck Go?
- Tags allow for substituting ingredients, making recommendations. imo too much upside not to implement; if not now then later (harder).
- Discuss how users can make use of ingredients not on the list. Approval? Allow then admin? More free for private recipes?

**Pull request closed without merging**
